[PF-161]: Multiple instance stairway support
DataBiosphere/terra-resource-buffer pull request #114
Opened 2021-02-10 12:36 UTC by yonghaoy

2021-02-16 17:39 UTC, gjuggler approved these changes
No major concerns, happy for this go in w/ another set of eyes and my nits & comments resolved

2021-02-16 17:39 UTC, gjuggler commented on src/main/java/bio/terra/buffer/app/configuration/StairwayConfiguration.java
> -  /**
[Side note] Does removing this configuration put a dependency on terra-helm/pull/286, where the chart change needs to be deployed before this code change? If so, it would be good to have a place to declare that depencency – maybe in the PF-161 ticket description (which is conspicuously blank so far)?

2021-02-16 20:30 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/stairway/StairwayComponent.java
> +    logger.info("Initializing Stairway...");
https://broadworkbench.atlassian.net/browse/PF-456

2021-02-16 21:53 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/app/configuration/KubernetesConfiguration.java
> +  private String podNameFilter = "buffer-service";
Added some comments. The purpose of the configuration is to construct common library's KubeService:
https://github.com/DataBiosphere/terra-common-lib/blob/develop/src/main/java/bio/terra/common/kubernetes/KubeService.java
Still not sure if my understanding is accurate. @ddietterich to confirm.

2021-02-16 22:00 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/app/configuration/StairwayConfiguration.java
> -  /**
Added more details in https://broadworkbench.atlassian.net/browse/PF-161.
Basically, that is the same process for all other similar changes: Terraform - Helm - Service code .

2021-02-16 22:02 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/app/configuration/KubernetesConfiguration.java
> +  private String podNameFilter = "buffer-service";
And I am not even sure if my understand is correct. Also asked question in another PR:
https://github.com/broadinstitute/terra-helm/pull/286#discussion_r576891239

2021-02-17 02:42 UTC, gjuggler approved these changes

2021-02-18 14:49 UTC, ddietterich requested changes
There is a thread safety problem with the status variable.
Otherwise, it looks good.

2021-02-18 14:49 UTC, ddietterich commented on src/main/java/bio/terra/buffer/service/stairway/StairwayComponent.java
> +    logger.info("Initializing Stairway...");
I was wondering if something like this whole component should be in the common lib.

2021-02-18 14:49 UTC, ddietterich commented on src/main/java/bio/terra/buffer/service/stairway/StairwayComponent.java
>        status = Status.ERROR;
I think maybe you should make `status` an Atomic or otherwise thread-safe. It is possible that Kubernetes requests shutdown while you are in this code. And possible for shutdown to be called multiple times. You would not want to make the transition from SHUTDOWN to OK, for example.

As far as I can tell, you only ever compare to OK outside this module.

I think it is incorrect to report the status of a library in the /status endpoint.

2021-02-18 14:54 UTC, ddietterich commented on src/main/java/bio/terra/buffer/app/configuration/KubernetesConfiguration.java
> +  private String podNameFilter = "buffer-service";
@gjuggler I see your point - from a week ago - about wanting consistent config params for the Kubernetes service. That is problematic for TDR, since they wouldn't match, but would be helpful for **everything else**.

Maybe making a wrapping `@Component` for KubeService that constructed the KubeService object from config params (like below) would be useful. TDR could use the base object until it is ready to convert. Everyone else could use the component. Maybe?

2021-02-18 16:06 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/stairway/StairwayComponent.java
>        status = Status.ERROR;
thanks! That is a good catch.

2021-02-18 16:19 UTC, gjuggler commented on src/main/java/bio/terra/buffer/app/configuration/KubernetesConfiguration.java
> +  private String podNameFilter = "buffer-service";
+1, I think that's a good model to work toward.

2021-02-18 16:36 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/app/configuration/KubernetesConfiguration.java
> +  private String podNameFilter = "buffer-service";
Similar to Dan's feedback on https://broadworkbench.atlassian.net/browse/PF-456 below, "the whole component can be in common library". So maybe we can have a common `KubeCompoment` in common library as well. But then it comes to the same slack discussion with Will: `@ConfigurationProperties` or constructor.

2021-02-18 17:00 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/app/configuration/KubernetesConfiguration.java
> +  private String podNameFilter = "buffer-service";
Or you want me to put the component here, everyone come here to copy-paste

2021-02-18 18:37 UTC, ddietterich approved these changes
LGTM

2021-02-18 18:37 UTC, ddietterich commented on src/main/java/bio/terra/buffer/app/configuration/KubernetesConfiguration.java
> +  private String podNameFilter = "buffer-service";
I figured you would get this working and then someone (I can do it, or you can) can work it into a PR for common lib.

2021-02-19 15:15 UTC, merged