project setup scripts  ca 1084  ca 1080
DataBiosphere/terra-resource-buffer pull request #120
Opened 2021-02-23 21:46 UTC by andy7i

2021-02-25 20:16 UTC, andy7i commented on src/main/resources/config/tools/resource-config/cwb_ws_resource_fiab_v3.yml
> +                 "group:terra-billing@quality.firecloud.org", "group:firecloud-project-owners@quality.firecloud.org" ]
since there are dev and qa fiabs, I added both quality.firecloud.org and test.firecloud.org

2021-02-25 20:16 UTC, andy7i commented on src/main/resources/config/dev/resource-config/aou_ws_resource_test_v3.yml
> +    - members: [ "group:terra-billing@test.firecloud.org", "group:firecloud-project-owners@test.firecloud.org" ]
these yamls were copied from the existing (v2) yamls and version bumped. The enabled APIs are the same as in DM. The members here were added to follow the DM model.

2021-02-25 20:16 UTC, andy7i commented on src/main/resources/config/perf/resource-config/resource_perf_v3.yml
> +      role: "roles/viewer"
these are the members that already existed in the perf and toolsalpha yamls so I left them in.

2021-02-25 22:40 UTC, yonghaoy requested changes
If you sync PR, you will see I just added staging and alpha...

2021-02-25 22:40 UTC, yonghaoy commented on src/main/resources/config/perf/pool_schema.yml
> +  - poolId: "resource_perf_v3"
The perf is RBS self test, it will not used by AoU or Rawls, so you don't need this.

2021-02-25 22:40 UTC, yonghaoy commented on src/main/resources/config/tools/resource-config/cwb_ws_resource_fiab_v3.yml
> +                 "group:terra-billing@quality.firecloud.org", "group:firecloud-project-owners@quality.firecloud.org" ]
is quality for perf test? That one we need another rawls-perf env for that. Perf traffic might be too much for tools RBS? I would want to know more details about that...
BTW, we don't have perf buffer setup yet.

2021-02-25 22:47 UTC, yonghaoy commented
And why not set it up in folder level? I that that is what we are doing today.

2021-02-26 19:46 UTC, gpolumbo-broad approved these changes
slight concern for the repetition needed in all of these.  Means when we add/remove one api we need to modify 4 different files.  But that's outside the scope of this PR.

2021-03-01 14:35 UTC, dvoet commented on src/main/resources/config/tools/resource-config/cwb_ws_resource_fiab_v3.yml
> +                 "group:terra-billing@quality.firecloud.org", "group:firecloud-project-owners@quality.firecloud.org" ]
@yonghaoy quality is also for fiab, not perf. Fiabs can run in 2 places: dev which uses test.firecloud.org and qa which uses quality.firecloud.org.

I don't think they should use the same pool though

2021-03-01 14:55 UTC, dvoet commented
why don't we add the groups to the folder?

2021-03-01 15:34 UTC, yonghaoy commented
> slight concern for the repetition needed in all of these. Means when we add/remove one api we need to modify 4 different files. But that's outside the scope of this PR.

We do realize that is a problem, having https://broadworkbench.atlassian.net/browse/PF-260 to track. But there is no plan to do it recently, but please let me know if you think it is important

2021-03-01 15:36 UTC, yonghaoy commented on src/main/resources/config/tools/resource-config/cwb_ws_resource_fiab_v3.yml
> +                 "group:terra-billing@quality.firecloud.org", "group:firecloud-project-owners@quality.firecloud.org" ]
I see, right now, there is no RBS&Janitor has permission on quality.firecloud.org, if we need such a pool, once we have that folder created, we also need to grant `tools` Janitor and RBS permission to that folder:
https://github.com/broadinstitute/terraform-ap-deployments/blob/master/terra-env/tfvars/tools.tfvars
(Add that folders in `buffer_external_folder_ids`, and `janitor_google_folder_ids`)

2021-03-04 15:13 UTC, andy7i commented
closing PR since the permissions are being set at the folder level now as part of https://github.com/broadinstitute/terraform-terra/pull/144

2021-03-04 15:13 UTC, closed without merging