PF-496: Add flags to control deletion of default Compute Engine SA and VPC network.
DataBiosphere/terra-resource-buffer pull request #123
Opened 2021-03-04 23:12 UTC by marikomedlock

The purpose of this change is to support running Nextflow against RBS-provided projects. Nextflow requires the default Compute Engine SA and the default VPC network to both exist. Previously, RBS always deletes these things. This PR adds flags to control this behavior, so we can turn it off in select environments.

In the long-term, we want to keep the current behavior (i.e. delete default SA and network). But that will likely require some contributions to the Nextflow codebase, and we want to use Nextflow for development in the meantime. So these flags are a near-term workaround.

***STILL TODO***
- Write tests. I'm just opening a PR now so that the GHA will run the existing tests for me, while I work on getting them running them locally.
- Investigate which config/*.yml files to update. Do I need to make a new file e.g. resource_toolsalpha_v3.yml or update an existing one? Which environment should I be modifying?
- Run tests against a deployed version in my personal environment.

2021-03-05 20:36 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectCreationFlight.java
> +    if (gcpProjectConfig.getComputeEngine() != null
I'm not sure this null check is needed. I think this is needed if I don't update all the .yml files under resources/config directory. But should I instead be updating all .yml files, so this is never null?

2021-03-05 20:38 UTC, marikomedlock commented on src/main/resources/config/toolsalpha/resource-config/resource_toolsalpha_v2.yml
> +    deleteDefaultServiceAccount: "false"
Should I be editing this file or creating a new _v3.yml instead?

2021-03-05 21:29 UTC, yonghaoy commented on src/main/resources/config/toolsalpha/resource-config/resource_toolsalpha_v2.yml
> +    deleteDefaultServiceAccount: "false"
resource configs are immutable, we do need v3.
But why we changing this? Which RBS will use deleteDefaultServiceAccount: "false" pool?

2021-03-05 21:29 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectCreationFlight.java
> +        && gcpProjectConfig.getComputeEngine().isDeleteDefaultServiceAccount()) {
we usually always add those steps but add config check inside those steps. 
Like
```
 if(gcpProjectConfig.getComputeEngine().isDeleteDefaultServiceAccount()) {
 return Step.successStep()
}
```

2021-03-05 21:29 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectCreationFlight.java
> +    if (gcpProjectConfig.getComputeEngine() != null
yeah, it does look wired, and if we keep adding things like that, it is also hard for us to track the exactly resource config, and know when to delete SA account, and when to not. 
But from your logic, seems all existings configs will stop deleting default SAs because their value is null.

I have been thinking about this recently, it is hard because the resource config is immutable, but as we keep adding new field in resource config schema, how to tell existing values which is the 'default value'? 
One solution, may not be the best, is to comment on the resource schema, saying what is the default value if not present. 
And when RBS populated those configs, we set some default values into DB. Logic is here:
https://github.com/DataBiosphere/terra-resource-buffer/blob/c319d27654cbd5910b978017c3e207dc57f221a8/src/main/java/bio/terra/buffer/service/pool/PoolService.java#L170
You can leave a null check, I can try to find a solution to fix that.

2021-03-05 21:35 UTC, yonghaoy commented
Actually, an easier solution, not to use ComputeEngine object, just add 'deleteDefaultComputeServiceAccount" in pool config directly, with a comment, default behaviour is false. 

And flight can check 
```
if deleteDefaultComputeServiceAccount != null && deleteDefaultComputeServiceAccount == true {
}
```

2021-03-05 22:43 UTC, marikomedlock commented on src/main/resources/config/toolsalpha/resource-config/resource_toolsalpha_v2.yml
> +    deleteDefaultServiceAccount: "false"
- I want WSM dev to have both delete flags set to "false". Would that be dev/workspace_manager_v6.yml? And then update terra-helmfile [here](https://github.com/broadinstitute/terra-helmfile/blob/902d123ec9e62403f1e1147543da616bc0f9ca3a/terra/values/workspacemanager/live/dev.yaml#L23)?

- I think it would be good to also have the option to set both delete flags to "false" in a personal environment. Would that be tools/workspace_manager_v5.yml? And then update terra-helmfile [here](https://github.com/broadinstitute/terra-helmfile/blob/902d123ec9e62403f1e1147543da616bc0f9ca3a/terra/values/workspacemanager/personal/mmedlock.yaml#L11)?

2021-03-05 22:48 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectCreationFlight.java
> +    if (gcpProjectConfig.getComputeEngine() != null
Okay, I'll change ComputeEngine.deleteDefaultServiceAccount object.property to just a property. Seems like we still need a solution to resource schema upgrade but if this is the only use case now, agreed it doesn't seem like we need to figure this out now.

2021-03-05 22:49 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectCreationFlight.java
> +        && gcpProjectConfig.getComputeEngine().isDeleteDefaultServiceAccount()) {
I can do that for the default SA step, but what about the firewall rules step? Should I expand that one to create rules for both networks?

2021-03-08 14:06 UTC, yonghaoy commented on src/main/resources/config/toolsalpha/resource-config/resource_toolsalpha_v2.yml
> +    deleteDefaultServiceAccount: "false"
What you said about personal environment and WSM is correct. 
For the toolsalpha, you don't need one that unless you want your personal RBS having that pool.

2021-03-08 14:17 UTC, yonghaoy requested changes

2021-03-08 14:17 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectCreationFlight.java
>      addStep(new CreateFirewallRuleStep(cloudComputeCow), CLOUD_API_DEFAULT_RETRY);
There is a CreateFirewallRuleStep

2021-03-08 14:17 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectCreationFlight.java
> +              cloudComputeCow, DeleteDefaultNetworkStep.DEFAULT_NETWORK_NAME),
Might be good to move this file if it becomes a common variable:
https://github.com/DataBiosphere/terra-resource-buffer/blob/master/src/main/java/bio/terra/buffer/service/resource/flight/GoogleUtils.java

2021-03-08 14:17 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/flight/CreateFirewallRuleStep.java
> +    this.allowInternalRuleName = ALLOW_INTERNAL_RULE_NAME;
This variable is not accurate now. Maybe ALLOW_INTERNAL_RULE_NAME_SUFFIX? or something else you think is better. Then add some comments to explain those two variables.

2021-03-08 14:17 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectCreationFlight.java
> +        && gcpProjectConfig.getComputeEngine().isDeleteDefaultServiceAccount()) {
I feel that is a better way. Take list of networks and create for each of them? Right now, two CreateFirewallRuleStep
 confuses me.

2021-03-08 15:12 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectCreationFlight.java
> +        && gcpProjectConfig.getComputeEngine().isDeleteDefaultServiceAccount()) {
Moved config logic out of steps and into flight. PTAL.

2021-03-08 15:13 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectCreationFlight.java
>      addStep(new CreateFirewallRuleStep(cloudComputeCow), CLOUD_API_DEFAULT_RETRY);
Modified that step to check the config, instead of calling it twice.

2021-03-08 15:13 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectCreationFlight.java
> +              cloudComputeCow, DeleteDefaultNetworkStep.DEFAULT_NETWORK_NAME),
done.

2021-03-08 19:43 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/service/resource/flight/CreateFirewallRuleStep.java
> +    this.allowInternalRuleName = ALLOW_INTERNAL_RULE_NAME;
Updated to have separate variables for each network's firewall rule names.

2021-03-09 15:18 UTC, yonghaoy approved these changes

2021-03-09 15:18 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/flight/CreateFirewallRuleStep.java
> +      DEFAULT_NETWORK_NAME + "-vpc-" + ALLOW_INTERNAL_RULE_NAME_FOR_NETWORK;
do we need 'vpc' in the middle? Not sure what is the usual practice for naming a firewall rule, but that does not seem to be a VPC.

2021-03-09 17:21 UTC, wchamber requested changes
lgtm other than couple of things on the CreateFirewallRuleStep

2021-03-09 17:21 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/flight/CreateFirewallRuleStep.java
> +  private List<OperationCow<?>> operationsToPoll = new ArrayList<>();
Avoid using mutable member variables if possible. Using mutable member variables data flow makes it harder to see what's supposed to happen in what order.

Instead of making `operationsToPoll` a member variable, keep it as a local variable in doStep and return an Optional<OperationCow<?>> from addFirewallRule. That makes the data flow and ordering explicit, instead of the implicit ordering that addFirewallRule should be called before the operations are polled.

Making `projectId` a mutable member variable saves us from passing it to `addFirewallRule`, but I think it's simple enough to add an argument there and not require explaining/relying on projectId is set at the beginning of `doStep`.

2021-03-09 17:57 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/service/resource/flight/DeleteDefaultNetworkStep.java
> +      return StepResult.getStepResultSuccess();
Yes, @yonghaoy requested this above. I originally had logic in the flight, not the steps. I don't have strong feelings though, prefer to be consistent with existing patterns in the codebase.

2021-03-09 17:57 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/service/resource/flight/CreateFirewallRuleStep.java
> +      if (keepDefaultNetwork(gcpProjectConfig)) {
Tickets already filed (PF-537, PF-538), will add TODOs in the code.

2021-03-09 17:57 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/service/resource/flight/CreateFirewallRuleStep.java
> +              .setNetwork(highSecurityNetwork.getSelfLink())
Good catch. Will update.

2021-03-09 19:47 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/service/resource/flight/GoogleUtils.java
> +  public static boolean keepDefaultNetwork(GcpProjectConfig gcpProjectConfig) {
will do. this was really confusing to me originally, and it seems easy to break for backwards compatibility. I think a wrapper around the proejct config would be a good addition.

2021-03-09 20:05 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/flight/CreateFirewallRuleStep.java
> +  private List<OperationCow<?>> operationsToPoll = new ArrayList<>();
I think not having mutable member variables is of value in itself. Returning the optional is just one way to make that work. I
One thing to consider is that Steps are instantiated on Flight construction. What happens when a Step is retried? Does Stairway call `doStep` on the same Step instance multiple times? What does our code start to do when it polls operations from previous tries? You could get around this by reinstantiating `operationsToPoll` at the start of each doStep, but it's easier to reason about if it's just a local variable instead of a member variable.

It's not very verbose with `Optional#map` and `Optional#ifPresent`

```
private Optional<OperationCow<?>> addFirewallRule(Firewall rule) throws IOException {
    return createResourceAndIgnoreConflict(() -> computeCow.firewalls().insert(projectId, rule).execute())
            .map(insertOperation -> computeCow.globalOperations().operationCow(projectId, insertOperation));
  }

// in doStep
addFirewallRule(allowInternal).ifPresent(operationsToPool::add);
```

2021-03-10 15:00 UTC, wchamber approved these changes
thanks!

2021-03-10 15:00 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/flight/CreateFirewallRuleStep.java
> +      // https://broadworkbench.atlassian.net/browse/PF-538
nit: We've been using a `// TODO(PF-538): ` todo style in comments in janitor, buffer, and workspace manager. worth being consistent?
ditto others

2021-03-10 15:36 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/service/resource/flight/CreateFirewallRuleStep.java
> +      // https://broadworkbench.atlassian.net/browse/PF-538
ok

2021-03-10 16:59 UTC, merged