[PF-456] Use common lib for stairway init
DataBiosphere/terra-resource-buffer pull request #128
Opened 2021-03-15 17:59 UTC by jaycarlton

goes with common lib PR https://github.com/DataBiosphere/terra-common-lib/pull/31

2021-03-15 21:11 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/app/StartupInitializer.java
> +    //    applicationContext.getBean(StairwayComponent.class).initialize();
We should keep it here, but  common-lib's StairwayComponent instead.

2021-03-17 17:10 UTC, jaycarlton commented on src/main/java/bio/terra/buffer/app/configuration/BufferJdbcThing.java
> +public class BufferJdbcThing extends JdbcProperties {
This is the bit that makes the least sense. It's not a `@Configuration` so I temporarily renamed it to thing.

2021-03-23 15:22 UTC, ddietterich reviewed
I'm curious about the `StairwayDatabaseConfiguration` class.
Otherwise, this looks good to me.

2021-03-23 15:22 UTC, ddietterich commented on build.gradle
> +    if (useMavenLocal) {
What is this for? And should it be part of this PR?
If it is a good thing, should we do it everywhere?

2021-03-23 15:22 UTC, ddietterich commented on src/main/java/bio/terra/buffer/app/configuration/StairwayDatabaseConfiguration.java
> +public class StairwayDatabaseConfiguration extends BaseDatabaseConfiguration {
Huh, I would have expected this to be in the common lib.

2021-03-23 16:47 UTC, jaycarlton commented on build.gradle
> +    if (useMavenLocal) {
Yes, it allows you to use locally deployed artifacts (like the common lib). I think it's a good thing. @gjuggler what do you think of this little paradigm?

I used the local repo extensively in testing this PR, so I didn't want to have to remove the maven local stuff.

2021-03-23 16:47 UTC, jaycarlton commented on src/main/java/bio/terra/buffer/app/configuration/StairwayDatabaseConfiguration.java
> +public class StairwayDatabaseConfiguration extends BaseDatabaseConfiguration {
Interesting. By what criteria? Sometimes it seemed arbitrary, and I went with the paths of least resistance.

2021-03-24 19:59 UTC, yonghaoy reviewed
We can not merge this PR before helm chart is updated with correct config: 
https://github.com/broadinstitute/terra-helm/blob/master/charts/buffer/templates/deployment.yaml#L137
The correct step should be: 
(1) Update helm chart to add the new configs,  e.g.  adding TERRA_COMMON_KUBERNETES_POD_NAME, 
TERRA_COMMON_BUFFER_KUBERNETES_POD_NAME_FILTER

(2) Wait until that PR merged, and deploied, merge this PR
(3) Delete those old configs from helm chart

2021-03-24 19:59 UTC, yonghaoy commented on build.gradle
> +    if (useMavenLocal) {
Or we can follow this instruction: https://github.com/DataBiosphere/terra-common-lib#local-testing
i.e, don't  add `mavenLocal` here. If engineer wants to test their change locally, then manually add temporary.

2021-03-24 19:59 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/app/StartupInitializer.java
> +import bio.terra.buffer.app.configuration.BufferDatabaseConfiguration;
thanks for doing this!

2021-03-24 20:12 UTC, yonghaoy requested changes

2021-03-24 20:12 UTC, yonghaoy commented on src/main/resources/application.yml
> -      username:
are you changing stairway DB configs?  I through we should still use this:
https://github.com/DataBiosphere/terra-resource-buffer/blob/master/src/main/java/bio/terra/buffer/app/configuration/StairwayDatabaseProperties.java
That means the config should still be `buffer.stairway.db`

2021-03-24 21:24 UTC, ddietterich commented on src/main/java/bio/terra/buffer/app/configuration/StairwayDatabaseConfiguration.java
> +public class StairwayDatabaseConfiguration extends BaseDatabaseConfiguration {
I would have thought Stairway database config would be processed in the common lib code, and not need to be present in the service code. I'm just trying to understand - not asking for any change.

2021-03-24 21:26 UTC, ddietterich commented on src/main/resources/application.yml
> -      username:
Seems like a trade-off between common setup (like in helm) for a stairway db, and getting config names that are specific to a service.

2021-03-24 21:27 UTC, ddietterich approved these changes
This looks fine to me. I don't understand all of the choices, but I don't see anything wrong.

2021-03-25 13:47 UTC, yonghaoy commented on src/test/resources/application-test.yml
>  terra.common:
merge with the tracing config. That is also terra.common

2021-03-25 13:47 UTC, yonghaoy commented on src/test/java/bio/terra/buffer/service/resource/FlightManagerTest.java
> +
remove newline

2021-03-25 13:47 UTC, yonghaoy commented on src/main/resources/application.yml
> -      username:
This seems to be wrong to me. I don't think the common-lib's prosperity has Stairway DB setup configs. Those are still in buffer code

2021-03-25 13:47 UTC, yonghaoy commented on src/test/java/bio/terra/buffer/common/PoolIdTest.java
> +    flightMap.put("key", 123);
that is this?

2021-03-25 13:53 UTC, jaycarlton commented on build.gradle
> +    if (useMavenLocal) {
This was intended as a prettier way to do that, so you don't have to dig in and find the spot to put `mavenLocal()`. You still have to bump version numbers though.

2021-03-25 13:53 UTC, jaycarlton commented on src/main/java/bio/terra/buffer/app/configuration/StairwayDatabaseConfiguration.java
> +public class StairwayDatabaseConfiguration extends BaseDatabaseConfiguration {
I never really landed on what felt like a good, intuitive boundary here. Might need to revisit at some point.

2021-03-25 13:53 UTC, jaycarlton commented on src/main/resources/application.yml
> -      username:
@yonghaoy are you saying this file needs a change? Have I orphaned a setting somewhere?

2021-03-25 14:32 UTC, yonghaoy requested changes
yo

2021-03-25 14:32 UTC, yonghaoy commented on src/main/resources/application.yml
> -  stairway:
you should add them back

2021-03-25 14:34 UTC, jaycarlton commented on src/test/java/bio/terra/buffer/common/PoolIdTest.java
> +    flightMap.put("key", 123);
I thought the map needed something in it to make the comparison meaningful. Otherwise it's just an empty structure, and might not catch as many bugs.

2021-03-25 18:59 UTC, jaycarlton commented on src/test/java/bio/terra/buffer/common/PoolIdTest.java
> +    flightMap.put("key", 123);
I just put something in the map to make the comparison non-trivial.

2021-03-25 19:05 UTC, yonghaoy commented on src/main/resources/application.yml
> +      force-clean-start: false
You also need to add the cluster suffix here?  the value should be buffer-stairwaycluster

2021-03-25 19:06 UTC, yonghaoy commented on src/main/resources/application.yml
> +      force-clean-start: false
And delete it from test's application.yml since your test doesn't need to override

2021-03-25 19:34 UTC, yonghaoy approved these changes

2021-03-25 22:56 UTC, merged