[CA-1139] Increase RBS Pool sizes to accommodate integration tests
DataBiosphere/terra-resource-buffer pull request #151
Opened 2021-05-14 16:42 UTC by s-rubenstein

This should increase the RBS dev pool sizes to 1000 (if I am understanding the configs correctly). This is an attempt to make the dev pool sizes large enough for the integration tests to run comfortably. I figure starting with 1000, we can increase by more over time as we see what our demand looks like.

2021-05-14 16:57 UTC, andy7i approved these changes
LGTM. One comment but not blocking.

2021-05-14 16:57 UTC, andy7i commented on src/main/resources/config/dev/pool_schema.yml
> +    size: 1000
not sure if these 2 are used enough to warrant an increase but I'm not too concerned about increasing it either

2021-05-14 18:23 UTC, yonghaoy requested changes
Per offline sync. Fiab is actually using `tools` RBS. And the error is not caused by pool limit

2021-06-24 19:46 UTC, gpolumbo-broad approved these changes

2021-06-24 20:03 UTC, closed without merging