[CA-1434] VPC pools for environments that don't already have one
DataBiosphere/terra-resource-buffer pull request #168
Opened 2021-06-30 20:15 UTC by andy7i

https://broadworkbench.atlassian.net/browse/CA-1434

2021-06-30 20:17 UTC, andy7i commented on src/main/resources/config/alpha/resource-config/cwb_ws_resource_alpha_v1.yml
> +    prefix: "terra-alpha"
does this require a v2 file/pool?

2021-06-30 20:17 UTC, andy7i commented on src/main/resources/config/alpha/resource-config/cwb_ws_resource_alpha_vpc_v1.yml
> +configName: "cwb_ws_resource_alpha_vpc_v1"
these yml's were copied from the non-vpc file. for example, this file ("cwb_ws_resource_alpha_vpc_v1.yml" was copied from "cwb_ws_resource_alpha_v1.yml" so they should be equivalent except for the configName and enableNetworkMonitoring (and maybe the "prefix").

2021-06-30 20:36 UTC, yonghaoy requested changes
VPC-SC GCP projects is only used by AoU at this moment.  And AoU only use Terra dev and prod. So I did not create vpc-sc pool in other envs. 
Is the requirement changing?

2021-06-30 20:36 UTC, yonghaoy commented on src/main/resources/config/alpha/resource-config/cwb_ws_resource_alpha_v1.yml
> +    prefix: "terra-alpha"
yes

2021-06-30 20:36 UTC, yonghaoy commented on src/main/resources/config/staging/resource-config/cwb_ws_resource_staging_v1.yml
> +    prefix: "terra-staging"
ditto, you need v2 here as well

2021-06-30 20:41 UTC, yonghaoy requested changes
See https://github.com/DataBiosphere/terra-resource-buffer/blob/d19530b63d2912386be6de85a1498c19f4898447/src/main/resources/config/dev/resource-config/vpc_sc_v1.yml as example. 
There is the pattern we use as discussed with in slack before:
1: config name: configName: "vpc_sc_v1"
2: You need to create those new folders in each env.  Example: test.firecloud.org/dev/for_vpc_sc_unclaimed
3: Prefix: terra-vpc-sc-{env}
4: pool name is also vpc_sc_v1
5: If no clients want to use those projects, I suggest not to create that large pool(20~100) is a reasonable pool size.

2021-06-30 20:43 UTC, yonghaoy commented on src/main/resources/config/alpha/resource-config/cwb_ws_resource_alpha_vpc_v1.yml
> +configName: "cwb_ws_resource_alpha_vpc_v1"
see mty another comment. The current pattern we are using. Config name can be `vpc_sc_v1`

2021-06-30 20:43 UTC, yonghaoy commented on src/main/resources/config/alpha/resource-config/cwb_ws_resource_alpha_vpc_v1.yml
> +  # test.firecloud.org/alpha/CommunityWorkbench
You should use another folder.

2021-06-30 20:43 UTC, yonghaoy commented on src/main/resources/config/tools/pool_schema.yml
> +    size: 500
500 is too large for a pool that no clients

2021-07-01 19:38 UTC, andy7i commented
@yonghaoy  thanks for the feedback!


> VPC-SC GCP projects is only used by AoU at this moment. And AoU only use Terra dev and prod. So I did not create vpc-sc pool in other envs.
> Is the requirement changing?

VPC-SC gcp projects can be used outside of AoU so this is to help set that up. I'm not 100% sure if we will need projects with network monitoring (and flow logs) outside of service perimeters, in which case maybe it makes sense to create a new pool for non-serviceperimeter projects?

Question for you:
why do perf and prod have `"notebooks.googleapis.com"`? (The other envs do not)

2021-07-02 11:22 UTC, yonghaoy commented
> @yonghaoy thanks for the feedback!
> 
> > VPC-SC GCP projects is only used by AoU at this moment. And AoU only use Terra dev and prod. So I did not create vpc-sc pool in other envs.
> > Is the requirement changing?
> 
> VPC-SC gcp projects can be used outside of AoU so we need to set up a pool for this scenario. We may also need projects with network monitoring (and flow logs) that will not use service perimeters, in which case maybe it makes sense to create a new pool for non-serviceperimeter projects since the current pool lives in `for_vpc_sc_unclaimed` folders? (I think part of this answer will come from https://broadworkbench.atlassian.net/browse/CA-1429)
> 
> Question for you:
> why do perf and prod have `"notebooks.googleapis.com"` for vpc and non-vpc pools? (The other envs do not have it. Should they? Looks like WSM also has it.)
> 
> ![Screen Shot 2021-07-01 at 5 38 11 PM](https://user-images.githubusercontent.com/5375000/124192429-4655ae00-da93-11eb-9a88-f544342350ea.png)

RE: Notebook API is optional for Rawls but required for WSM(WSM supports creates Cloud API Notebook, but I don't know if Rawsl needs). I may copied/paste from WSM template when setting up Rawls Prod. I think you can leave as it or add that API for other envs in case Rawls need to support Terra-cli(https://github.com/DataBiosphere/terra-cli/tree/main/notebooks). Sorry for the confusion.

2021-07-02 11:29 UTC, yonghaoy approved these changes

2021-07-02 11:29 UTC, yonghaoy commented on src/main/resources/config/staging/resource-config/vpc_sc_v1.yml
> +    prefix: "terra-vpc-sc-staging"
FYI: GCP has name prefix of 30 character. This is already 21(including the extra - appended). 
But it should still work here because we hard coded the random char after it is 8
https://github.com/DataBiosphere/terra-resource-buffer/blob/master/src/main/java/bio/terra/buffer/service/resource/projectid/GcpProjectIdGenerator.java#L20

2021-07-06 21:23 UTC, andy7i commented
> > @yonghaoy thanks for the feedback!
> > > VPC-SC GCP projects is only used by AoU at this moment. And AoU only use Terra dev and prod. So I did not create vpc-sc pool in other envs.
> > > Is the requirement changing?
> > 
> > 
> > VPC-SC gcp projects can be used outside of AoU so we need to set up a pool for this scenario. We may also need projects with network monitoring (and flow logs) that will not use service perimeters, in which case maybe it makes sense to create a new pool for non-serviceperimeter projects since the current pool lives in `for_vpc_sc_unclaimed` folders? (I think part of this answer will come from https://broadworkbench.atlassian.net/browse/CA-1429)
> > Question for you:
> > why do perf and prod have `"notebooks.googleapis.com"` for vpc and non-vpc pools? (The other envs do not have it. Should they? Looks like WSM also has it.)
> > ![Screen Shot 2021-07-01 at 5 38 11 PM](https://user-images.githubusercontent.com/5375000/124192429-4655ae00-da93-11eb-9a88-f544342350ea.png)
> 
> RE: Notebook API is optional for Rawls but required for WSM(WSM supports creates Cloud API Notebook, but I don't know if Rawsl needs). I may copied/paste from WSM template when setting up Rawls Prod. I think you can leave as it or add that API for other envs in case Rawls need to support Terra-cli(https://github.com/DataBiosphere/terra-cli/tree/main/notebooks). Sorry for the confusion.

Ideally we wouldn't have any extraneous permissions. I think we should check with @broad-dsp-appsec to see if it's ok for the terra/rawls projects in the prod and perf environments to have the extra api enabled.

2021-07-06 21:54 UTC, jacmrob reviewed
I'm assuming `prod` and `dev` already have have VPC pools?

2021-07-06 21:54 UTC, jacmrob commented on src/main/resources/config/alpha/pool_schema.yml
> +- poolId: "vpc_sc_v1"
what does sc stand for?

2021-07-06 21:54 UTC, jacmrob commented on src/main/resources/config/alpha/resource-config/cwb_ws_resource_alpha_v2.yml
> +  billingAccount: "01A82E-CA8A14-367457"
is it okay that this is hard-coded?

2021-07-06 21:54 UTC, jacmrob commented on src/main/resources/config/alpha/resource-config/cwb_ws_resource_alpha_v2.yml
> +    prefix: "terra-alpha"
so do these get created in their own google projects then rather than the projects that correlate with their environments?

2021-07-06 21:54 UTC, jacmrob commented on src/main/resources/config/alpha/pool_schema.yml
> +- poolId: "vpc_sc_v1"
and what are the two pools (`cwb_ws...` and `vpc_sc...`) in each environment for?

2021-07-06 21:54 UTC, jacmrob commented on src/main/resources/config/alpha/resource-config/vpc_sc_v1.yml
> +    prefix: "terra-vpc-sc-alpha"
curious on choice of naming schema... if `vpc_sc_v1` -> `terra-vpc-sc-alpha`, should `cwb_ws_resource_alpha_v2` -> `terra-cwb-ws-resource-alpha`? 

Not asking that it be changed if this is consistently the naming convention in the repo. maybe understanding the difference between these two pools will help too.

2021-07-06 22:07 UTC, marctalbott approved these changes
Looks good. Plus one to keeping the enabled apis across environments standardized. The more we can keep our projects homogenous the better.

2021-07-07 12:41 UTC, yonghaoy commented
> > > @yonghaoy thanks for the feedback!
> > > > VPC-SC GCP projects is only used by AoU at this moment. And AoU only use Terra dev and prod. So I did not create vpc-sc pool in other envs.
> > > > Is the requirement changing?
> > > 
> > > 
> > > VPC-SC gcp projects can be used outside of AoU so we need to set up a pool for this scenario. We may also need projects with network monitoring (and flow logs) that will not use service perimeters, in which case maybe it makes sense to create a new pool for non-serviceperimeter projects since the current pool lives in `for_vpc_sc_unclaimed` folders? (I think part of this answer will come from https://broadworkbench.atlassian.net/browse/CA-1429)
> > > Question for you:
> > > why do perf and prod have `"notebooks.googleapis.com"` for vpc and non-vpc pools? (The other envs do not have it. Should they? Looks like WSM also has it.)
> > > ![Screen Shot 2021-07-01 at 5 38 11 PM](https://user-images.githubusercontent.com/5375000/124192429-4655ae00-da93-11eb-9a88-f544342350ea.png)
> > 
> > 
> > RE: Notebook API is optional for Rawls but required for WSM(WSM supports creates Cloud API Notebook, but I don't know if Rawsl needs). I may copied/paste from WSM template when setting up Rawls Prod. I think you can leave as it or add that API for other envs in case Rawls need to support Terra-cli(https://github.com/DataBiosphere/terra-cli/tree/main/notebooks). Sorry for the confusion.
> 
> Ideally we wouldn't have any extraneous permissions. I think we should check with @broad-dsp-appsec to see if it's ok for the terra/rawls projects in the prod and perf environments to have the extra api (which is already enabled for WSM projects) enabled.

Or we can create a new pool without the extra permissions in prod and perf if we want

2021-07-07 14:20 UTC, andy7i commented on src/main/resources/config/alpha/pool_schema.yml
> +- poolId: "vpc_sc_v1"
the SC stands for Service Control which is used for controlling access and data exfiltration https://cloud.google.com/vpc-service-controls

I'm following the existing naming schemes -- `cwb_ws` stands for community workbench workspace, which is the "regular" project type in terra. The vpc_sc projects are used for projects that live inside a service perimeter.

2021-07-07 14:20 UTC, andy7i commented on src/main/resources/config/alpha/resource-config/cwb_ws_resource_alpha_v2.yml
> +    prefix: "terra-alpha"
they get created into the org/folder that is specified by `parentFolderId` on lines 8-9 below. In this case, it is created in `test.firecloud.org/alpha/CommunityWorkbench` (dev, alpha, perf, staging all live in the test.firecloud.org org)

2021-07-07 14:20 UTC, andy7i commented on src/main/resources/config/alpha/resource-config/cwb_ws_resource_alpha_v2.yml
> +  billingAccount: "01A82E-CA8A14-367457"
I do think ideally we would be able to get the billingAccount and enabledApis (below) from a config file so that we don't have to copy/paste these into each yml, but I don't think we can do that yet.

2021-07-07 14:20 UTC, andy7i commented on src/main/resources/config/alpha/resource-config/vpc_sc_v1.yml
> +    prefix: "terra-vpc-sc-alpha"
I'm mainly following the existing naming convention here. I think the vpc_sc pools will be used primarily for AoU, so maybe that's why?

2021-07-07 14:58 UTC, yonghaoy commented on src/main/resources/config/alpha/resource-config/vpc_sc_v1.yml
> +    prefix: "terra-vpc-sc-alpha"
I am not sure what would be the best name prefix. That name came from: https://github.com/DataBiosphere/terra-resource-buffer/pull/145#discussion_r614068570

2021-07-08 15:02 UTC, andy7i commented
I'll handle the perf and prod changes as part of a separate PR to keep things more contained.

2021-07-08 15:06 UTC, andy7i commented
> I'm assuming `prod` and `dev` already have have VPC pools?

yep!

2021-07-08 15:11 UTC, jacmrob commented on src/main/resources/config/alpha/pool_schema.yml
> +- poolId: "vpc_sc_v1"
Gotcha, thanks

2021-07-08 15:11 UTC, jacmrob commented on src/main/resources/config/alpha/resource-config/cwb_ws_resource_alpha_v2.yml
> +  billingAccount: "01A82E-CA8A14-367457"
Okay, no problem

2021-07-08 15:13 UTC, jacmrob approved these changes
Lgtm

2021-07-08 15:17 UTC, andy7i commented
@yonghaoy github tells me `Merging is blocked The base branch restricts merging to authorized users. Learn more about protected branches.` Should we have access to merge to master? / could you merge it?

2021-07-08 16:03 UTC, yonghaoy commented
> @yonghaoy github tells me `Merging is blocked The base branch restricts merging to authorized users. Learn more about protected branches.` Should we have access to merge to master? / could you merge it?

Hi @andy7i The repo access was messed up when I setup 2 reviewer policy with GHA auto push. Now it should be fixed. Can you try again?

2021-07-08 16:10 UTC, merged

2021-07-08 16:10 UTC, andy7i commented
@yonghaoy works for me now -- thanks!