Yyu pf 184 -dev RBS
DataBiosphere/terra-resource-buffer pull request #59
Opened 2020-11-17 16:29 UTC by yonghaoy

2020-11-17 19:43 UTC, gjuggler commented on src/main/resources/config/dev/resource-config/aou_ws_0_0_1.yml
> +  parentFolderId: "637867149294"
I'd add a comment here clarifying what folder this points to, e.g.

```# test.firecloud.org/terra_dev_aou_test```

2020-11-17 19:43 UTC, gjuggler commented on src/main/resources/config/dev/resource-config/cwb_ws_0_0_1.yml
> +    enableNetworkMonitoring: "true"
Unless you've already done so, best to double-check w/ @dvoet whether network monitoring should be turned on for projects in the CWB pool. The main practical impacts would be

(1) private Google access, which works fine for AoU but would require some testing / validation with CWB apps, and which also incurs some small additional cost due to the use of Cloud DNS.
(2) VPC flow logs, which result in additional Cloud Logging storage cost. Though default retention is 30 days, so it's unlikely to cause a meaningful uptick in cost to users.

2020-11-19 15:28 UTC, yonghaoy commented on src/main/resources/config/dev/resource-config/aou_ws_0_0_1.yml
> +  parentFolderId: "637867149294"
done.

2020-11-19 15:29 UTC, yonghaoy commented on src/main/resources/config/dev/resource-config/cwb_ws_0_0_1.yml
> +    enableNetworkMonitoring: "true"
Thanks, the version you reviewed was my local testing version. Now the PR is ready for review. Thanks!

2020-11-19 18:43 UTC, gjuggler requested changes

2020-11-19 18:43 UTC, gjuggler commented on src/main/resources/config/dev/pool_schema.yml
> +  - poolId: "aou_ws_test_v1"
nit / suggestion: I'd add a comment above this line to give space for a more long-form description of what this pool is and who it serves. (Do the same for the CWB pool too.)

Possible comment text for this pool:

"Pool for GCP projects to be used by workspaces in the AoU test environment. Rawls is the proximal owner of these projects; AoU sits as a layer atop Rawls."

2020-11-19 18:43 UTC, gjuggler commented on src/main/resources/config/dev/resource-config/aou_ws_0_0_1.yml
> +  parentFolderId: "737976594150"
Hmm -- just thinking aloud, it seems likely that we're going to end up with many near-duplicate resource configs where the only diff between environments is the parentFolderId. Maybe it's not worth doing immediately, but a scheme where the pool config could override some subset of the resource config might provide a way to reduce that duplication.

2020-11-19 18:43 UTC, gjuggler commented on src/main/resources/config/dev/resource-config/aou_ws_0_0_1.yml
>      - "dns.googleapis.com"
nit: alphabetize all API entries (here and in all other resource configs)

2020-11-19 18:43 UTC, gjuggler commented on src/main/resources/config/tools/pool_schema.yml
> +  - poolId: "cwb_ws_test_v1"
broken record, but what is "test"? That's not a CWB environment or a Terra environment name. Maybe this would be clearer with a comment describing the pool's use case in words... but I also think a different short-token would be clearer. Maybe "cwb_ws_fiab_v1" if this is meant to provide a pool to be used by FIAB CWB tests?

2020-11-19 18:43 UTC, gjuggler commented on src/main/resources/config/dev/resource-config/aou_ws_0_0_1.yml
>  # All Of Us buffered workspace template
General note: what is the purpose of the pseudo-semantic-versioning used in the filename? Given that the configName only has a "v1" suffix, is there any benefit of having a different versioning format for the filename? My instinct would be to align them to keep things simple & consistent.

2020-11-19 18:43 UTC, gjuggler commented on src/main/resources/config/toolsalpha/pool_schema.yml
> +  - poolId: "ws_resource_toolsalpha_v1"
I think "ws" is meant to represent "workspace", but arguably this pool for RBS integration testing has nothing to do with workspaces – right? This comment applies to all of the above pool IDs as well. Is there an important reason why "ws" is part of all these names? If it's universally used, then it doesn't seem to provide much differentiating power.

2020-11-19 18:43 UTC, gjuggler commented on src/main/resources/application.yml
> +    config-path: config/toolsalpha
This is an interesting change. Can you add a comment clarifying why exactly we refer to toolsalpha from this file? I suspect the answer is "point to toolsalpha for local testing" but it's very helpful to make that explicit here since it's kind of non-obvious.

2020-11-19 18:59 UTC, yonghaoy commented on src/main/resources/config/dev/resource-config/aou_ws_0_0_1.yml
> +  parentFolderId: "737976594150"
yeah, I realized it as well.  The current config loading logic is simple, we pass in the entire configPath directory name and assume that the files are already well oranizaed in this simple way. 
Is there any exsiting exampels/well-known pattern about yaml override in the similar scenario?

2020-11-19 19:01 UTC, yonghaoy commented on src/main/resources/config/tools/pool_schema.yml
> +  - poolId: "cwb_ws_test_v1"
Changed to fiab_.  Thanks!

2020-11-19 20:05 UTC, yonghaoy commented on src/main/resources/config/toolsalpha/pool_schema.yml
> +  - poolId: "ws_resource_toolsalpha_v1"
removed `ws` Thanks

2020-11-19 20:07 UTC, yonghaoy commented on src/main/resources/application.yml
> +    config-path: config/toolsalpha
Thanks for pointing out. Now I feel toolsalpha shouldn't be here. I am not setting any default values now. And will set it in run_local.sh and helmfile instead. 
https://github.com/broadinstitute/terra-helmfile/pull/613
But I will keep the configPath: record with the readme and comment here.

2020-11-19 22:07 UTC, gjuggler approved these changes
Thanks for the changes!

2020-11-20 14:36 UTC, merged