[DO NOT REVIEW YET] PF-237: Use Test Runner library to write tests using client library.
DataBiosphere/terra-resource-buffer pull request #67
Opened 2020-11-24 15:46 UTC by marikomedlock

This PR contains the first pass at using the Test Runner library to write client tests for Buffer Service.

- Added a buffer-clienttests Gradle project.
- Include a server specification for a developer namespace in the terra-integration cluster.
- Write one test that hits the unauthenticated endpoint, and one that hits the unauthenticated endpoint.

2020-11-25 15:05 UTC, yonghaoy requested changes
Thanks for doing this! 
Overrall I have some questions about how we can use it?  For now, this seems to have some to many SA json files and not well managed. I don't think it will work for me or other developers. I think we need a better piping secret & config piping scenarios here. 
Happy to chat if you have time after standup. Woud be great if @gjuggler can also help on those configs management stuff. 

Thanks!

2020-11-25 15:05 UTC, yonghaoy commented on buffer-clienttests/build.gradle
> +spotbugs {
I think recently Issac standerlize WM/Janitor/RBS build.gradle file. And they don't have those spotbugs stuff. Do we need those? Shall we follow the same pattern like RBS's build.gradle or we should add this into the standard?

2020-11-25 15:36 UTC, gjuggler commented on local-dev/setup_gke_deploy.sh
> +git clone -b "$TERRA_HELM_BRANCH" --single-branch git@github.com:broadinstitute/terra-helm.git
cloning from HTTPS URLs for private GitHub repos requires interactively typing username and password on the command-line. That feels like an awkward side-effect of a setup script, and it's also painful for folks who use a password for GitHub that isn't in muscle memory.

What problems did you run into getting set up with SSH for GitHub? AFAIK it's a very common setup — it may be worth working through solutions for those issues.

(Obviously this is separate thread from this PR, we can follow-up after standup or in slack)

2020-11-25 16:04 UTC, yonghaoy commented on local-dev/setup_gke_deploy.sh
> +git clone -b "$TERRA_HELM_BRANCH" --single-branch git@github.com:broadinstitute/terra-helm.git
Somehow I don't need to type my username and password when using https urls. But I got some authentication issue when using ssh. I think it's same for Will recently:
https://github.com/DataBiosphere/terra-resource-janitor/pull/62#issuecomment-729756525
I can try to setup my ssh again.. There might be some steps we missed.

2020-11-30 17:21 UTC, marikomedlock commented on local-dev/setup_gke_deploy.sh
> +git clone -b "$TERRA_HELM_BRANCH" --single-branch git@github.com:broadinstitute/terra-helm.git
Okay, I'll put it back to HTTPS until we have consensus on the approach in Terra code.

2020-11-30 17:26 UTC, marikomedlock commented on buffer-clienttests/src/main/resources/testusers/neville.json
> +  "name": "neville",
Per our conversation last week, I'll remove these users and the associated SA since you're not planning to use domain-wide delegated credentials for Buffer Service.

For the other questions:
- These test users are not Data Repo-specific. All services that end users can talk to directly will probably want to do some testing with user credentials rather than service credentials. Currently in Data Repo (and my understanding also other existing Terra services), we do that with domain-wide delegated user credentials.
- Domain-wide delegated user credentials require a SA that can get credentials on behalf of a user. We cannot create this in Terraform because domain-wide delegation is a GSuite thing, not a GCP thing, and requires some manual steps to setup. For this reason, I think we should just use one SA that can get domain-wide delegated credentials for all services. Data Repo already has one that we use for this -- it isn't used anywhere else.

2020-11-30 17:28 UTC, marikomedlock commented on buffer-clienttests/src/main/resources/serviceaccounts/jade-k8-sa.json
> +  "jsonKeyDirectoryPath": "/tmp"
This SA is to support domain-wide delegation. Per our conversation last week, I'll remove this since you're not planning to use domain-wide delegation to test Buffer Service.

2020-11-30 17:30 UTC, marikomedlock commented on buffer-clienttests/src/main/java/scripts/utils/BufferServiceUtils.java
> +    // apiClient.setDebugging(true); // useful for debugging problems header sent/received
Removed, it was just for debugging.

2020-11-30 17:31 UTC, marikomedlock commented on buffer-clienttests/src/main/resources/configs/BasicAuthenticated.json
> +      "expectedTimeForEach": 5,
Yes, we could always specify things in seconds or whatever we want for the smallest time unit. Since some of the user journeys in Data Repo could take a long time (~hours), it made the test specifications more readable to use larger units.

2020-11-30 17:33 UTC, marikomedlock commented on buffer-clienttests/src/main/java/scripts/testscripts/ServiceStatus.java
> +  public void userJourney(TestUserSpecification testUser) throws Exception {
I don't follow your comment. userJourney already is a method of TestScript (the base class that ServiceStatus extends) that must be overridden. Can you rephrase?

2020-11-30 17:35 UTC, marikomedlock commented on buffer-clienttests/build.gradle
> +spotbugs {
I used spotbugs because it is in the MC Terra Tech Stack [document](https://docs.google.com/document/d/1JkTrtaci7EI0TnuR-68zYgTx_mRCNu-u2eV9XhexWTI/edit#heading=h.dndcg044j2p). What are you using for static analysis instead?

2020-11-30 17:36 UTC, marikomedlock commented on buffer-clienttests/settings.gradle
> +        // To use a local copy of the Test Runner library, uncomment the flatDir block and comment out the maven block
Removed debugging code.

2020-11-30 17:37 UTC, marikomedlock commented on buffer-clienttests/src/main/java/scripts/utils/BufferServiceUtils.java
> +    AccessToken accessToken = AuthenticationUtils.getAccessToken(serviceAccountCredential);
Yes, scopes are set on the SA credential to the (user login) scopes "openid", "email", "profile".

2020-11-30 17:42 UTC, marikomedlock commented on buffer-clienttests/src/main/java/scripts/utils/BufferServiceUtils.java
> +    if (server.bufferUri == null || server.bufferUri.isEmpty()) {
I don't see Guava listed in the MC Terra tech stack [document](https://docs.google.com/document/d/1JkTrtaci7EI0TnuR-68zYgTx_mRCNu-u2eV9XhexWTI/edit#).

But it seems services can make their own decisions about which libraries to include, so I added this dependency to the buffer-clienttests project.

2020-11-30 17:45 UTC, marikomedlock commented on buffer-clienttests/settings.gradle
> +                if (requested.id.namespace == "bio.terra") {
This logic tells Gradle where to find the JAR that contains the TestRunner Gradle plugin. The purpose of the plugin is so that each project that contains tests doesn't have to copy/paste the same Gradle tasks.

2020-11-30 17:50 UTC, marikomedlock commented on buffer-clienttests/src/main/java/scripts/utils/BufferServiceUtils.java
> +public class BufferServiceUtils {
Added.

2020-11-30 17:57 UTC, marikomedlock commented on buffer-clienttests/src/main/resources/configs/BasicUnauthenticated.json
> +  "billingAccount": "00708C-45D19D-27AAFA",
Data Repo clients need to specify a billing account to use when creating resources, so this is just a test configuration property. It's not required though, so I'll just remove it since Buffer Service isn't using it now.

2020-11-30 17:59 UTC, marikomedlock commented on buffer-clienttests/src/main/resources/configs/BasicUnauthenticated.json
> +  "serverSpecificationFile": "yyu-dev.json",
Yes, the server specification can be [overridden](https://github.com/DataBiosphere/terra-test-runner#override-the-server-from-the-command-line) by an environment variable.

2020-11-30 18:02 UTC, marikomedlock commented on buffer-clienttests/src/main/resources/serviceaccounts/mmedlock-buffer-client-sa.json
> +  "jsonKeyDirectoryPath": "../src/test/resources/rendered"
Okay so do I need a separate render-configs script for testing that pulls the RBS client SA account from Vault?

2020-11-30 18:08 UTC, marikomedlock commented on buffer-clienttests/src/main/resources/servers/mmedlock-dev.json
> +{
An instance of the ServerSpecification class (= JSON files in the resources/servers directory) represents a single Terra environment or deployment. So we should have a single JSON file for each environment that we want to run tests against. I was thinking this will include at least one developer namespace in terra-integration cluster where you can debug, and one for each environment where performance/resilience tests need to be run periodically. In Data Repo, this includes perf, alpha, and staging.

2020-11-30 18:43 UTC, marikomedlock commented
Thanks for the review. I marked the conversations resolved where I didn't have a question - please reopen with any follow-ups.

Agreed about needing a better way to manage config/secrets piping. However, I don't think that should block development of client tests. In the long-term, I think we should be able to point to a Terra environment/deployment with a single keyword (e.g. terra-integration-mmedlock, rbs-perf, preview-env-123) and then derive all the other information relevant to clients from that. Relevant information for clients includes: service urls, client SAs (or maybe Vault paths to their credentials), any additional information about connections between the services (e.g. SAM resource id that corresponds to the particular Data Repo instance). One way to derive all this information is to look it up in a Kubernetes config map.

Since we don't have this config/secrets management solution yet, the Test Runner library uses a manual specification of a Terra environment/deployment. The intention is that we can replace this manual specification with a dynamic lookup of Terra environment properties (e.g. service URLs) once the Kubernetes config map (or other) solution is available.

This is a summary of my thoughts on this. But maybe this topic is better to discuss in a meeting. @yonghaoy What do you think?

2020-11-30 21:19 UTC, yonghaoy commented on buffer-clienttests/src/main/resources/serviceaccounts/mmedlock-buffer-client-sa.json
> +  "jsonKeyDirectoryPath": "../src/test/resources/rendered"
Yes, I think we need a script like this: https://github.com/DataBiosphere/terra-resource-buffer/blob/master/local-dev/render-config.sh
And I suggest to create a new script for the test runner SAs in its own package.

2020-11-30 21:21 UTC, yonghaoy commented on buffer-clienttests/src/main/java/scripts/testscripts/ServiceStatus.java
> +  public void userJourney(TestUserSpecification testUser) throws Exception {
Ah, I didn't realize userJourney already a method of TestScript. If that is the case, I think you miss `@override` annotation here.
Should be 
```
@Override
public void userJourney(TestUserSpecification testUser) throws Exception {
```

2020-11-30 21:22 UTC, yonghaoy commented on buffer-clienttests/build.gradle
> +spotbugs {
Ah, I see. Then I think RBS & WM are missing this thing

2020-11-30 21:35 UTC, yonghaoy commented
Thanks! @marikomedlock Overrall the test runner looks good to me. But I am little bit confused about how to actually make this thing useful. This including:

1. How /when / where to trigger this test runner. (in release process? nightly run? or something else)? 
2. What envs we need for this and what additional the CI/CD work we need?
3. I think we won't have preview env ready recently but RBS needs to go to production soon, how can we use this without preview environment? 

Thanks

2020-12-01 22:33 UTC, marikomedlock commented on buffer-clienttests/src/main/resources/serviceaccounts/mmedlock-buffer-client-sa.json
> +  "jsonKeyDirectoryPath": "../src/test/resources/rendered"
Got it. I added one, PTAL.

2020-12-01 22:34 UTC, marikomedlock commented on buffer-clienttests/src/main/java/scripts/testscripts/ServiceStatus.java
> +  public void userJourney(TestUserSpecification testUser) throws Exception {
Ah I understand. Yes good point. Added the annotations.

2020-12-01 22:57 UTC, marikomedlock commented
Thanks for the helpful comments and pointer to the render-config example.

Test Runner should run in:
- GH actions. I don't know what the frequency should be -- I think that is independent of Test Runner, and probably we should have some conversation with Greg or QA about the recommended approach.
- Local machine. This is for writing and debugging tests, and for running one-time profiling experiments (e.g. to determine appropriate config value)

Agreed about not waiting for preview environments to be ready. I think we should run Test Runner tests against environments/deployments that are already setup manually (e.g. developer namespace, perf/alpha/staging/dev). This is what Data Repo currently does.

With this branch, you should be able to write a performance test and run it against an existing environment. This was the first goal. There are some more changes coming:
- Ivan will probably write some example GH actions, based on existing Data Repo examples. Once those are ready, we can put an example in this branch.
- We will make some changes to Test Runner library to support resilience tests. Once that is ready, we can also put an example in this branch.

So I'll plan to leave this branch here, not merged, and re-request your review when the above changes are ready. In the meantime, you can try to write performance tests if you'd like, or wait until all features are available.

2021-02-02 01:10 UTC, yonghaoy approved these changes
You can go ahead and merge it, and I will have a follow up PR to setup it in github action.

Thanks!

2021-02-02 01:13 UTC, merged