[test perf]fix test
DataBiosphere/terra-resource-buffer pull request #90
Opened 2020-12-22 00:14 UTC by yonghaoy

2021-01-06 15:38 UTC, marikomedlock requested changes
Comments/questions inline.

2021-01-06 15:38 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/db/BufferDao.java
> +            : Optional.empty();
What does it mean when this update doesn't return 1? I think it means that there were 2 requests that picked the same ready resource. One of the requests successfully updated the state and request_handout_id, and the other request's update here fails. Is that right? Regardless, a comment here explaining the situation would be very helpful.

2021-01-06 15:38 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/db/BufferDao.java
> +                + " WHERE id = :id AND request_handout_id IS null";
Do you also want to have state=READY in the where clause here? I'm not sure if it's necessary or not -- I think only if it's possible for a READY resource to have its state changed without having its request_handout_id set.

2021-01-06 15:38 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/service/pool/PoolService.java
> +              10);
This means to do 10 retries with a timeout of 2 seconds each? Please add a comment here.

2021-01-06 15:38 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/service/pool/PoolService.java
>        PoolId poolId, RequestHandoutId requestHandoutId, TransactionStatus unused) {
Nit: add method comment. In particular, explaining what you mean by "transactionally" I think would be helpful.

2021-01-06 15:38 UTC, marikomedlock commented on src/test/java/bio/terra/buffer/db/BufferDaoTest.java
> +    bufferDao.createResource(newResource(pool2.id(), HANDED_OUT));
Nit: Don't import the static here, so it matches the above lines.

2021-01-06 15:38 UTC, marikomedlock commented on src/test/java/bio/terra/buffer/service/resource/FlightSchedulerTest.java
> +        resources, (Matcher) Matchers.hasItems(resourceArgumentCaptor.getAllValues().toArray()));
I don't follow what you are testing here. You start with a pool with 5 resources, 4 of which are ready. Then you retrieve all 4 ready resources. Then you are checking that ...?

2021-01-06 15:38 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/db/BufferDao.java
> +        return existingResource;
Nit: Add a log statement to this block indicating that we already handed this resource out.

Also, under what conditions would the same request try to update a single resource to ready more than once -- is this to support Stairway retries maybe?

2021-01-06 15:38 UTC, marikomedlock commented on src/test/java/bio/terra/buffer/db/BufferDaoTest.java
> +    Resource resource = newResource(pool.id(), HANDED_OUT);
Nit: Don't import the static to match elsewhere in this file.

2021-01-06 15:38 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/db/BufferDao.java
> +   * </ul>
Great summary here thanks, also I like the new method name better.

2021-01-06 16:28 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/db/BufferDao.java
> +            : Optional.empty();
The sql above has `where id==.` make sure there will be only 1 get updated as most. 
The value here is more 1 or 0(if anything cause update failed somehow). I just use Optional instead of null to control the workflow. That is common practice in Buffer&Janitor to use 
`jdbcTemplate.update(sql, params) == 1` in every update/delete single row statement. Added a comment.

2021-01-06 16:34 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/db/BufferDao.java
> +                + " WHERE id = :id AND request_handout_id IS null";
Added. Just to confirm: The resource is retrieved from `retrieveResourcesRandomly(READY)` above.  The whole method is wrapped 
`@Transactional(propagation = Propagation.REQUIRED, isolation = Isolation.SERIALIZABLE)`
Does that means the to be updated resource is locked in READY state?

2021-01-06 16:36 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/pool/PoolService.java
> +              10);
added

2021-01-06 16:51 UTC, yonghaoy commented on src/test/java/bio/terra/buffer/service/resource/FlightSchedulerTest.java
> +        resources, (Matcher) Matchers.hasItems(resourceArgumentCaptor.getAllValues().toArray()));
the test behaviors doesn't change(4 are ready but scheduler should only delete), but we need to change the code to fix test breakage. 
The scheduler scans db and pick the X number ready resources it should delete. 
Previously, it always pick the top X resources(limit X in sql). So the previous test just pick the top 3 and verify it matches. 
Now it uses select randomResource(and it should). So I need to retrieve all 4 ready now, and verify 3 of them are deleted.

2021-01-06 16:56 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/db/BufferDao.java
> +        return existingResource;
Done. 
Retries happens in client side to make sure traffic is not dropped. Client caches the requestHandoutId and use that to retry if they didn't get resource back.

2021-01-08 20:37 UTC, marikomedlock approved these changes
LGTM

2021-01-08 20:37 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/db/BufferDao.java
> +        return existingResource;
Got it, thanks.

2021-01-08 20:37 UTC, marikomedlock commented on src/main/java/bio/terra/buffer/db/BufferDao.java
> +                + " WHERE id = :id AND request_handout_id IS null";
Yes, I think that's right. But just seems safer since it's in two separate methods, in case we add new callers in the future.

2021-01-09 13:30 UTC, merged