[no ticket]: TranscationTemplate should swallow exceptions
DataBiosphere/terra-resource-buffer pull request #97
Opened 2021-01-15 01:19 UTC by yonghaoy

Context:  I saw there is a CREATING state resource stays in DB but there is no such record in stairway Flight. After digging into logs. I suspect TranscationTemplate doesn't propagate exceptions, and ignore exceptions being catched. 
So I made the PR to verify my throught.

If that looks reasonable, I would delete _withTryCatch() methods and merge this PR

2021-01-15 14:00 UTC, yonghaoy commented
I don't think the codacy complains are reasonable..

2021-01-15 14:33 UTC, gjuggler commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +    try {
What is the purpose of this try-catch and re-throw? Is there any obvious benefit compared to just allowing the exception to bubble up directly to the transaction manager?

2021-01-15 14:33 UTC, gjuggler commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +    } catch (RuntimeException e) {
Is it important to catch all exceptions here and return an empty value? At the very least, if we're catching all RuntimeExceptions we should log out the exception message before returning, so the stack traces show up in our logs.

2021-01-15 15:00 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +    try {
This method is one part of the scheduler service scheduling flight. We don't want scheduler to continue even one flight submit failed.

2021-01-15 15:06 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +    } catch (RuntimeException e) {
This method is one part of the scheduler service scheduling flight. We don't want scheduler to continue even one flight submit failed.
Added logs

2021-01-15 15:41 UTC, gjuggler commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +    try {
OK. To confirm my understanding then, the conversion of checked exceptions into a runtime exception is a key part of causing the txn to be appropriately rolled back? It's worth adding a comment to the re-throw line to make its role in this process explicit, to help future readers of this code know what's important and why.

2021-01-15 15:42 UTC, gjuggler approved these changes

2021-01-15 15:57 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +    try {
[TransactionTemplate#execute](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/support/TransactionTemplate.html#execute-org.springframework.transaction.support.TransactionCallback-)'s [TransactionCallback](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/support/TransactionCallback.html) cannot throw checked exceptions by its signature. So if we throw a checked exception in our code executed as the TransactionCallback, we must rethrow it as a runtime exception to compile. If we don't rethrow, then the exception is lost and the TransactionTemplate#execute never sees the exception.
Alternatively, we could set the [TransactionStatus#setRollback](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/TransactionExecution.html#setRollbackOnly--) when we catch the checked exception, which also notifies the TransactionTemplate that we must roll back.

2021-01-15 16:19 UTC, wchamber requested changes

2021-01-15 16:19 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +    } catch (RuntimeException e) {
Please add a comment to that effect.

2021-01-15 16:19 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +  /** Submit Stairway Flight to create resource.  TODO: Remove before submit. */
TODO remove before submit?

2021-01-15 16:19 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +    } catch (RuntimeException e) {
ditto comment

2021-01-15 16:19 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +  /** TODO: Remove before submit. */
TODO remove before submit

2021-01-15 16:19 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +        flightSubmissionFactory.getCreationFlightSubmission(pool, resourceId));
If the flight submission has a try-catch, then we won't roll back the transaction if the flight submission fails. In that case, we'll have a CREATING resource sitting around without a Flight - effectively leaking the resource I think?

Oh, it is leaking, and the test verifies that... Am I supposed to be seeing with the two ways, that one doesn't work and one does? I'm ready to review the code that we're trying to submit.

2021-01-15 16:19 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +   * TODO: Remove before submit.
these TODOs are confusing me.

2021-01-15 16:19 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/flight/StepUtils.java
> +      new RetryRuleFixedInterval(/* intervalSeconds =*/ 60, /* maxCount =*/ 10);
why are we messing with the cloud api  & internal retry in this PR?

2021-01-15 16:23 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +  /**
(This should be on lines 76-87. I can't comment on code not in the PR - thanks github.)

I don't think it's correct to create the resource & submit to stairway within a single transaction. Can the transaction commit fail after a successful submission to Stairway? If it does, we'll rollback the created resouce in the dao, but we have no way of rolling back the Stairway submission.

2021-01-15 16:24 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +  /**
@gjuggler I think this is why we had the Janitor pattern of not including calls to Stairway within the database transaction. I've changed my mind that I think this is ok.

2021-01-15 16:24 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +        flightSubmissionFactory.getCreationFlightSubmission(pool, resourceId));
All the TODO _withTryCatch is to demonstrate my thought(see my PR description).
After you and Greg reviewed the old leaking version with test, now I am removing those

2021-01-15 16:25 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/flight/StepUtils.java
> +      new RetryRuleFixedInterval(/* intervalSeconds =*/ 60, /* maxCount =*/ 10);
sorry, that was messed up from another PR

2021-01-15 16:28 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +        flightSubmissionFactory.getCreationFlightSubmission(pool, resourceId));
Oops. Sorry. From the description "After digging into logs. I suspect TranscationTemplate doesn't propagate exceptions, and ignore exceptions being catched." I don't know what you mean by this. It doesn't magically propagate exceptions that don't bubble up to it? If the exception is caught within the TransactionCallback, then yes, it will not cause a rollback.
Also, we can't rollback stairway submissions with a TransactionTemplate - TransactionTemplate doesn't know anything about Stairway.

2021-01-15 16:34 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +    try {
Yup, I just saw the 2nd approach from an article. And I think that would be better, Switch to the new way

2021-01-15 16:34 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +    } catch (RuntimeException e) {
removed

2021-01-15 16:34 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +  /**
I think submittToQueue is another postgres db commit call eventually, and I think it should able to rollback. 
And the flight will get rollback if resource in a wrong state.
Currently the checks happens as the last step of the flight (when we update state from DB). 
I can add a step at beginning of the flight to check the state, and let Flight fail earlier.

2021-01-15 16:44 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +  /**
Ah, I forgot we were trying to handle this in the flight itself.
What happens if the flight fails fatally? Then we don't have a DB entry, but we may have leaked a project. I guess we have to go and manually debug all fatal flights?

It's very much worth some comments about what's going on here.

2021-01-15 16:56 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +  /**
I'm trying to remember all the discussion we had here with Dan. I think this pattern of submitting to stairway in the transaction & having the flight rollback if the resource didn't get created came out of a doc you wrote Yonghao. The alternative was the complicated Janitor logic of monitoring for resources that were not successfully submitted or finished. Do you know where all that discussion lived?
Do we have tests for the case where a creation/deletion flight runs when the transaction kicking it off failed?

2021-01-15 16:56 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +  /**
Just added two steps at the begining of the flight to assert resource state correct. 
There is not too much we can do if flight fails fatally. The current rollback was two steps : 
1. Delete project
2. Delete DB
 The only thing we can do is to investigate which steps it fails, and manually cleanup things(it hasn't happen to me so far).

2021-01-15 16:59 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +        flightSubmissionFactory.getCreationFlightSubmission(pool, resourceId));
(1) I was just trying to say I saw transcation was leaked
(2) Feels that is a general problems of using TransactionTemplate, we don't really know how the sub-steam libraries we use implemented. But we use different libraries all the time. 
And to me using TransactionTemplate was more like to make sure our own db get rollbacked if something went wrong. 
And actually, I suspect Stairway can rollback as the code to TransactionTemplate is just another DB(in stairway DB) commit eventually

2021-01-15 19:50 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +        flightSubmissionFactory.getCreationFlightSubmission(pool, resourceId));
2) In general, you should not do anything other than query your db during a transaction. No API calls, no calls to other services, including Stairway. You can make exceptions, but carefully.
Today, Stairway cannot roll back as a part of the Spring TransactionTemplate. Stairway is connecting to a different database and isn't using any of the Spring magic. I'ts not obvious to me we'd want to support allowing its modifications to be undone as a part of a transaction.
We can verify this is the case:
```
String flightId = "foo"
transactionTemplate.execute(status -> { stairway.submitFlight(...); throw new RuntimeException(); });
stairway.getFlight(flightId);  // Does the flight submission exist even though the transaction was rolled back?
```

2021-01-15 20:07 UTC, wchamber requested changes

2021-01-15 20:07 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/flight/AssertResourceCreatingInDbStep.java
> + * submitting flight success but updating DB fails.
there's a race here, which may cause us to leave a resource in CREATING. Nothing forces the transaction around submission to finish before this step executes.
1. Transaction begins
2. Create resource in CREATING (pending transaction completeness).
3. Submit Flight successfully.
4. Flight begins executing.
5. This step executes, causes the flight to fail fatally as the resource does not exist yet.
6. Transaction completes, creating the resource with state CREATING.

Now there's a race between 5 & 6. If 4 executes first, the resource is stuck in CREATING with a fatal flight. Even worse, the race is likely to cause one of these transactions to fail since they're trying to read the same row. In general, it's not safe to use transactions with Stairway. Pragmatically, we can retry this step a few times. So that step execution always happens at least once after transaction completes.
This is also the case for DELETING. Working with transactions & Stairway is very tricky.

2021-01-15 20:07 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/flight/AssertResourceCreatingInDbStep.java
> + * Checks if resource exists and in DELETING state before the actual deletion. It may happen when
s/DELETING/CREATING ?

2021-01-15 20:07 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/flight/AssertResourceCreatingInDbStep.java
> +public class AssertResourceCreatingInDbStep implements Step {
optional nit: I'd be fine removing `InDb` from both these class names.

2021-01-15 20:07 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/flight/AssertResourceDeletingInDbStep.java
> +    // Do nothing. We just use this step's undo method.
ditto

2021-01-15 20:07 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/flight/AssertResourceCreatingInDbStep.java
> +package bio.terra.buffer.service.resource.flight;
I think there should be a test exercising these assertion steps for each of the flights.

2021-01-15 23:05 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/flight/AssertResourceCreatingInDbStep.java
> + * submitting flight success but updating DB fails.
Oh, there is the race. Thanks! I will let the step return error and retry on it.

2021-01-15 23:15 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +        flightSubmissionFactory.getCreationFlightSubmission(pool, resourceId));
Yeah, we need to have the extra check step like I the one I added

2021-01-15 23:19 UTC, yonghaoy commented on src/main/java/bio/terra/buffer/service/resource/flight/AssertResourceCreatingInDbStep.java
> +package bio.terra.buffer.service.resource.flight;
> I think there should be a test exercising these assertion steps for each of the flights.

Currently we have Flight integration tests that touches all steps of the flight. Feel that is enough for a success case. 
For failure, do we want to exercise failure test, I feel this logic is straight forward so I didn't add this. Adding test for a failure requires requires 200> lines change, and I don't think that worth the effort.

2021-01-19 19:58 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
>        // checked exception and we need to manually set it up.
nit: `// If the flight submission fails, set the transaction to be rolled back.`

2021-01-19 19:58 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/flight/AssertResourceCreatingStep.java
> +    // but the flight begins and it reaches here.
nit: fix comment whitespace

2021-01-19 19:58 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/flight/AssertResourceDeletingStep.java
> +    // but the flight begins and it reaches here.
nit: ditto wwhiteespace

2021-01-19 19:58 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +   * bad state.
nit: ditto wordsmithing

2021-01-19 19:58 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/FlightManager.java
> +   * bad state.
nit: some wordsmithing
`// If the Stairway submission fails, the transaction will be rolled back. If the Stairway submission succeeds and t the DB update transaction fails, the flight checks the DB state and aborts if the state is bad.`

2021-01-19 19:58 UTC, wchamber commented on src/main/java/bio/terra/buffer/service/resource/flight/AssertResourceCreatingInDbStep.java
> +package bio.terra.buffer.service.resource.flight;
It's not so much that I'm worried that the code we have now is wrong for the failure case, it's that I'd like to have the test so that we don't accidentally break it by changing the code later. This is a subtle race bug, which is the best kind of thing to have a test on.
I'd imagine the test looks like

1. Create the resource in the DAO.
2. Start flight with scheduler. This flight starts with a latch step before any other steps.
3. Delete the resource in the DAO.
4. Resume the latch step.
5. Verify the flight is aborted and no project was created.

We should be in a spot where it's not hard to write these kinds of tests, but if that's not the case, fine.

2021-01-21 18:16 UTC, wchamber approved these changes
sorry for the slow turnaround.

2021-01-21 18:16 UTC, wchamber commented on src/test/java/bio/terra/buffer/integration/CreateProjectFlightIntegrationTest.java
> +    }
no work needed: I wish there was a cleaner way to do this, but I think we have to do it this way.

2021-01-21 18:16 UTC, wchamber commented on src/test/java/bio/terra/buffer/service/resource/flight/LatchStep.java
> +    System.out.println("~~~~~~~LatchStep");
nit: remove this?

2021-01-21 18:16 UTC, wchamber commented on src/test/java/bio/terra/buffer/integration/CreateProjectFlightIntegrationTest.java
> +  public void testCreateGoogleProject_errorWhenResourceStateChange() throws Exception {
is there a related test for resource deletion? the resource deletion flight gets submitted, but the transaction to mark the resource as deleting fails. subsequently, the same resource gets handed out.

2021-01-23 18:01 UTC, merged